config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    # コントローラにdeviseが見当たらないのはgemにあるから
    get '/login', to: 'devise/sessions#new', as: 'login'
    post '/login', to: 'devise/sessions#create', as: 'sign_in'
    delete '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end
  
  devise_scope :user do
    # カスタムセッションのルーティング
    get 'admin/login', to: 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/login', to: 'admin/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admin do
    get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
    resources :users, except: [:index]  # indexを除外
    get 'users', to: 'dashboard#index', as: 'admin_dashboard_users'  # 新しいルーティングを追加
    resources :users
  end

  resources :attendances, only: [:create] do
    collection do
      get 'show_monthly_logs'
    end
  end
  
  root "home_pages#home"
  get "/home", to: "home_pages#home", as: 'home'
  get "/admin", to: "home_pages#admin", as: 'admin'
  get "/member", to: "home_pages#member", as: 'member'
  get "/signup", to: "users#new", as: 'signup'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  get '/attendance', to: 'attendances#create', as: 'attendance'
  post '/sognup', to: 'devise/sessions#create', as: 'sign_up'

  resources :users
  resources :attendances, only: [:create, :index] 
  resources :attendances do
    post 'undo', on: :collection
  end
  post 'undo_attendance', to: 'attendances#undo'
  post 'attendances/redo', to: 'attendances#redo', as: 'redo_attendance'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  private

  def require_admin
    redirect_to new_admin_login_path unless current_user&.admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @user = current_user
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<%= render 'layouts/headerhome' %>
<div class="container">

	<h2><%= current_user.name %></h2>
	<p>adminモード</p>
	<%= render 'layouts/attendanceform' %>

    <h1>All Users</h1>
    <table class="users-table">
        <thead>
            <tr>
                <th>名前</th>
                <th>職種</th>
                <th>時給</th>
                <th>状態</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr class="user-show">
                    <td><%= user.name %></td>
                    <td>
                        <% if user.ptj == true %>
                            アルバイト
                        <% else %>
                            社員
                        <% end %>
                    </td>
                    <td>
                        <%= user.wage %>
                    </td>
                    <td>
                        <% if user.retire == true %>
                            退職
                        <% else %>
                            　
                        <% end %>
                    </td>
                    <td>
                    <%= link_to '詳細', admin_user_path(user), class: 'btn btn-allusers' %>
                    <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-allusers' %>
                    <%= button_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-allusers' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <br>

	<%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-logout" %>
</div>