config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    # コントローラにdeviseが見当たらないのはgemにあるから
    get '/login', to: 'devise/sessions#new', as: 'login'
    post '/login', to: 'devise/sessions#create', as: 'sign_in'
    delete '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end
  
  devise_scope :user do
    # カスタムセッションのルーティング
    get 'admin/login', to: 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/login', to: 'admin/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end

  namespace :admin do
    get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
    resources :users, except: [:index]  # indexを除外
    get 'users', to: 'dashboard#index', as: 'admin_dashboard_users'  # 新しいルーティングを追加
    resources :users
  end

  resources :attendances, only: [:create] do
    collection do
      get 'show_monthly_logs'
    end
  end
  
  root "home_pages#home"
  get "/home", to: "home_pages#home", as: 'home'
  get "/admin", to: "home_pages#admin", as: 'admin'
  get "/member", to: "home_pages#member", as: 'member'
  get "/signup", to: "users#new", as: 'signup'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  get '/attendance', to: 'attendances#create', as: 'attendance'
  post '/sognup', to: 'devise/sessions#create', as: 'sign_up'

  resources :users
  resources :attendances, only: [:create, :index] 
  resources :attendances do
    post 'undo', on: :collection
  end
  post 'undo_attendance', to: 'attendances#undo'
  post 'attendances/redo', to: 'attendances#redo', as: 'redo_attendance'
end

app/views/layouts/_attendanceform.html.erb
<%= link_to '出勤情報', attendance_path, class: "btn btn-logout" %>

<%= form_tag(attendances_path, method: :post) do %>

	<% next_action = current_user.next_attendance_action %>
	
	<%= button_tag(type: 'submit', name: "attendance_type", value: "0", class: "btn btn-attendance btn-0", disabled: next_action != :attendance) do %>
		出勤
	<% end %>
	<%= button_tag(type: 'submit', name: "attendance_type", value: "1", class: "btn btn-attendance btn-1", disabled: next_action != :break_or_leave) do %>
		休憩
	<% end %>
	<%= button_tag(type: 'submit', name: "attendance_type", value: "2", class: "btn btn-attendance btn-2", disabled: next_action != :break_end) do %>
		戻り
	<% end %>
	<%= button_tag(type: 'submit', name: "attendance_type", value: "3", class: "btn btn-attendance btn-3", disabled: next_action != :break_or_leave) do %>
		退勤
	<% end %>

<% end %>
  

app/views/layouts/_header.html.erb
<header class="navbar">
	<%= link_to image_tag('logo.png', alt: 'Logo', id: 'logo'), home_path %>
	<div class="spacer"></div>  
	<ul>
		<li><%= link_to "Home", home_path %></li>
		<li><%= link_to "Member", member_path %></li>
		<li><%= link_to "Admin", admin_path %></li>
	</ul>
</header>

app/views/layouts/_headerhome.html.erb
<header class="navbar">
	<%= link_to image_tag('logo.png', alt: 'Logo', id: 'logo'), home_path %>
	<div class="spacer"></div>
	<ul>
		<li lang="en"><%= link_to "Home", home_path%></li>
		<li lang="en"><%= link_to "Member", member_path %></li>
		<li lang="en"><%= link_to "Admin", new_user_session_path %></li>
	</ul>
</header>

app/views/layouts/_headeruser.html.erb
<header class="navbar">
	<%= link_to image_tag('logo.png', alt: 'Logo', id: 'logo'), home_path %>
	<div class="spacer"></div>  
	<ul>
		<li><%= link_to "Home", home_path %></li>
		<li><%= link_to "Admin Top", admin_path %></li>
		<li><%= link_to "All User", "#" %></li>
	</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= favicon_link_tag 'favicon.ico' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
    <div class="container">
      <div class="contents">
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>

  </body>
</html>